language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.1.1
  - 2.2.2
script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_install:
  - gem update --system
  - gem --version
  - cp config/database.yml.example config/database.yml
