language: ruby
rvm:
  - 1.9.3
script:
  - cp config/database.yml.example config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_install:
  - gem update --system
  - gem --version

